version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Building static website..."
      - echo "No build steps needed for static HTML"
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  name: static-website